</center><img src="coverage_workflow_image.png"  width="1000" height="300"/></center>

In [50]:
# import required python libraries
#import geopandas as gpd  # for geo-data structure
import numpy as np  # for some operation better done with numpy
import matplotlib.pyplot as plt  # for creating plots
#import shapely.geometry  # for geometry data crunching
#from shapely.geometry import Point  # specifically for point geometry data manipulation
#import keplergl
#from keplergl import KeplerGl
import datacompy
import pandas as pd
crs = {'init': 'epsg:4326'}
#from shapely.geometry import Point
import mpl_toolkits

In [2]:
# bring in the 3 to 4 different coverage dataset from FB, GSMA, ITU and Ericsson as well as the master school_geolocation

In [55]:
d_f = pd.read_csv('./data/RW_FB_data_20210608.csv',low_memory=False,encoding='utf-8')
d_i = pd.read_csv('./data/coverage_data_itu.csv',low_memory=False,encoding='utf-8')
d_e = pd.read_csv('./data/Rwanda_Ericsson_07_06_2021.csv',low_memory=False,encoding='utf-8')
d_g = pd.read_csv('./data/GSMA_RW_Schools_mobile_coverage_v1.csv',low_memory=False,encoding='utf-8')
s_master = pd.read_csv('./data/rwanda_school_geolocation_master.csv',low_memory=False,encoding='utf-8')

In [78]:
d_g.head(10)

,sn,source_sch,school_nam,school_cat,school_set,district,sector,cell,village,latitude,...,connectivi,giga_school_id,2G,3G,4G,coverage,2G_coverage,3G_coverage,4G_coverage,coverage_type
0,1,430710.0,GS MURAMA,PUBLIC,12 YBE,RUTSIRO,MASASA,GABIRO,GABIRO,-1.973667,...,3G,G_RWA_00001,3.0,3.0,3.0,YES,YES,YES,YES,4G
1,2,521312.0,GS MUHORORO,PUBLIC,12 YBE,KARONGI,MURAMBI,MUHORORO,BWAKIRA,-2.159389,...,3G,G_RWA_00002,3.0,NaN,3.0,YES,YES,NO,YES,4G
2,3,120515.0,GS MWENDO,PUBLIC,12 YBE,RUHANGO,MWENDO,GAFUNZO,NYAMIGINA,-2.166806,...,3G,G_RWA_00003,3.0,3.0,3.0,YES,YES,YES,YES,4G
3,4,120122.0,GS KIMISANGE,PUBLIC,12 YBE,KICUKIRO,KIGARAMA,BWERANKORI,NYENYERI,-1.989889,...,3G,G_RWA_00004,3.0,3.0,3.0,YES,YES,YES,YES,4G
4,5,331220.0,GS MWENDO,PUBLIC,12 YBE,GICUMBI,MUKO,MWENDO,KAGOGO,-1.730639,...,3G,G_RWA_00005,3.0,NaN,3.0,YES,YES,NO,YES,4G
5,6,411305.0,GS NYAGISOZI,PUBLIC,12 YBE,NYANZA,CYABAKAMYI,KARAMA,NYABINOMBE,-2.295028,...,3G,G_RWA_00006,3.0,NaN,3.0,YES,YES,NO,YES,4G
6,7,430323.0,GS RWAMIKO,PUBLIC,12 YBE,RUTSIRO,MANIHIRA,HANIRO,KAZIRAMIHUNDE,-1.939389,...,3G,G_RWA_00007,3.0,1.0,NaN,YES,YES,YES,NO,3G
7,8,510402.0,GS KIGARAMA,PUBLIC,12 YBE,KIREHE,KIGARAMA,KIGARAMA,SAMUKO,-2.333917,...,3G,G_RWA_00008,3.0,3.0,3.0,YES,YES,YES,YES,4G
8,9,510619.0,GS RUGANGO,PUBLIC,12 YBE,KIREHE,MUSAZA,KABUGA,RUGANGO,-2.371833,...,3G,G_RWA_00009,3.0,NaN,NaN,YES,YES,NO,NO,2G
9,10,521042.0,GS NYABISINDU,PUBLIC,12 YBE,GATSIBO,KIRAMURUZI,NYABISINDU,AKABUGA,-1.830611,...,3G,G_RWA_00010,3.0,3.0,3.0,YES,YES,YES,YES,4G

In [69]:
d_g['coverage'].value_counts()

YES    4181
NO       16
Name: coverage, dtype: int64

In [4]:
# some colunm names standardization

In [58]:
d_e.rename(columns={'SCHOOL_CODE':'school_id', 'SCHOOL_NAME':'school_name'}, inplace=True)
d_i.rename(columns={'giga_schoo': 'giga_school_id','source_sch':'school_id', 'name':'school_name'}, inplace=True)
d_g.rename(columns={'giga_schoo': 'giga_school_id'}, inplace=True)

In [59]:
# cross-profiles the sources with master data for completeness and correctness

In [60]:
# create a separate dfs
master = s_master.copy()
fb = d_f.copy()
ec = d_e.copy()
itu = d_i.copy()
gsma = d_g.copy()
# for facebook
cross_profile_fb_master = datacompy.Compare(
master,
fb,
join_columns='giga_school_id',  
df1_name='Master', 
df2_name='Facebook'
)
#for ericsson
cross_profile_e_master = datacompy.Compare(
master,
ec,
join_columns='giga_school_id',  
df1_name='Master', 
df2_name='Ericsson'
)
# for ITU
cross_profile_itu_master = datacompy.Compare(
master,
itu,
join_columns='giga_school_id',  
df1_name='Master', 
df2_name='ITU'
)
# for GSMA
cross_profile_gsma_master = datacompy.Compare(
master,
gsma,
join_columns='giga_school_id',  
df1_name='Master', 
df2_name='GSMA'
)
print(cross_profile_fb_master.report())
print(cross_profile_e_master.report())
print(cross_profile_itu_master.report())
print(cross_profile_gsma_master.report())

DataComPy Comparison
--------------------

DataFrame Summary
-----------------

  DataFrame  Columns  Rows
0    Master       20  4093
1  Facebook       26  4195

Column Summary
--------------

Number of columns in common: 12
Number of columns in Master but not in Facebook: 8
Number of columns in Facebook but not in Master: 14

Row Summary
-----------

Matched on: giga_school_id
Any duplicates on match values: No
Absolute Tolerance: 0
Relative Tolerance: 0
Number of rows in common: 4,091
Number of rows in Master but not in Facebook: 2
Number of rows in Facebook but not in Master: 104

Number of rows with some compared columns unequal: 8
Number of rows with all compared columns equal: 4,083

Column Comparison
-----------------

Number of columns compared with some values unequal: 1
Number of columns compared with all values equal: 11
Total number of values which compare unequal: 8

Columns with Unequal Values or Types
------------------------------------

        Column Master dtype Facebook dtype  # Unequal  Max Diff  # Null Diff
0  school_name       object         object          8         0            0

Sample Rows with Unequal Values
-------------------------------

     giga_school_id                        school_name (Master)                          school_name (Facebook)
3433    G_RWA_03526                       LITTLE GEMS ACADEMY""                       "LITTLE GEMS ACADEMY"""""
3459    G_RWA_03553                   NKERENKE PRIMARY SCHOOL""                   "NKERENKE PRIMARY SCHOOL"""""
2396    G_RWA_02434                                GS MUGANZA""                                "GS MUGANZA"""""
3972    G_RWA_04077                       St Christopher TVET""                       "St Christopher TVET"""""
3833    G_RWA_03936                               PSST KIZITO""                               "PSST KIZITO"""""
634     G_RWA_02502  IBYIRINGIROBYEJO SAINTE MARIE MONTESORIE""  "IBYIRINGIROBYEJO SAINTE MARIE MONTESORIE"""""
2185    G_RWA_02214                                GS MWEGERA""                                "GS MWEGERA"""""
3717    G_RWA_03817                          LycÃ©e de Rusatira                               Lycée de Rusatira

Sample Rows Only in Master (First 10 Columns)
---------------------------------------------

                                      uuid country      source giga_school_id  source_school_id                              school_name education_level  latitude  longitude             hex8
2413  b4037996-d127-4111-84ee-73f082241cec  Rwanda  government    G_RWA_02451          250205.0  GROUPE SCOLAIRE SAINT\n NICOLAS CYANIKA       Secondary -2.442110   29.60156  886ad85947fffff
2576  f6220be6-13a4-45ae-b000-327bbb048733  Rwanda  government    G_RWA_02626          121312.0               Ecole Notre Dame des Anges         Primary -1.956555   30.00000  886ad8c6d3fffff

Sample Rows Only in Facebook (First 10 Columns)
-----------------------------------------------

       tile_bigint  clean_lat  clean_lon  school_id      sn  source_school_id  school_name   school_category        school_settings   district
4121  2.630250e+15  -1.753333  30.251667      436.0   436.0          450504.0    GS KAGOGO            PUBLIC                  12YBE    GICUMBI
4141  2.626950e+15  -2.567880  29.987665     1392.0  1392.0          280910.0  EP KAGARAMA            PUBLIC                PRIMARY    KAMONYI
4153  2.632320e+15  -1.257083  30.417083      199.0   199.0          521307.0    GS KABEZA  GOVERNMENT_AIDED                  12YBE  NYAGATARE
4124  2.627040e+15  -1.971278  29.995056      147.0   147.0          281208.0   GS RUYENZI            PUBLIC                  12YBE    KAMONYI
4182  2.635720e+15  -2.035250  30.688944      621.0   621.0          130523.0   EP BYIMANA            PUBLIC  "PRE_PRIMARY,PRIMARY"    KAYONZA
4128  2.623710e+15  -2.496056  29.728667      253.0   253.0          241003.0   GS RUGOGWE  GOVERNMENT_AIDED                  12YBE       HUYE
4178  2.627400e+15  -1.757333  30.024083      192.0   192.0          410503.0   GS GIHINGA  GOVERNMENT_AIDED                  12YBE    RULINDO
4154  2.628200e+15  -1.456944  30.088111      290.0   290.0          451706.0   GS MUYUMBU  GOVERNMENT_AIDED                  12YBE    GICUMBI
4145  2.634160e+15  -1.675083  30.564028     1027.0  1027.0          540609.0    EP GAKOMA            PUBLIC                PRIMARY    KAYONZA
4114  2.620380e+15  -2.579778  29.463056     1207.0  1207.0          121014.0   EP MUYANGE            PUBLIC                PRIMARY  NYAMAGABE


DataComPy Comparison
--------------------

DataFrame Summary
-----------------

  DataFrame  Columns  Rows
0    Master       20  4093
1  Ericsson       39  4197

Column Summary
--------------

Number of columns in common: 11
Number of columns in Master but not in Ericsson: 9
Number of columns in Ericsson but not in Master: 28

Row Summary
-----------

Matched on: giga_school_id
Any duplicates on match values: No
Absolute Tolerance: 0
Relative Tolerance: 0
Number of rows in common: 4,093
Number of rows in Master but not in Ericsson: 0
Number of rows in Ericsson but not in Master: 104

Number of rows with some compared columns unequal: 1
Number of rows with all compared columns equal: 4,092

Column Comparison
-----------------

Number of columns compared with some values unequal: 1
Number of columns compared with all values equal: 10
Total number of values which compare unequal: 1

Columns with Unequal Values or Types
------------------------------------

        Column Master dtype Ericsson dtype  # Unequal  Max Diff  # Null Diff
0  school_name       object         object          1         0            0

Sample Rows with Unequal Values
-------------------------------

     giga_school_id                     school_name (Master)                 school_name (Ericsson)
2413    G_RWA_02451  GROUPE SCOLAIRE SAINT\n NICOLAS CYANIKA  GROUPE SCOLAIRE SAINT NICOLAS CYANIKA

Sample Rows Only in Ericsson (First 10 Columns)
-----------------------------------------------

        sn  school_id        school_name   school_category      school_settings    district      sector        cell      village  latitude
4132   375   560202.0           GS MBUYE            PUBLIC                12YBE       NGOMA      JARAMA      KIGOMA       MUBAHA -2.279778
4191  1342   110207.0         EP MUGANZA            PUBLIC              PRIMARY  NYARUGENGE  KIMISAGARA  KIMISAGARA      MUGANZA -1.953139
4128   342   331109.0         GS MURAMBI  GOVERNMENT_AIDED                12YBE      RUBAVU      RUBAVU     BURINDA       BUBAJI -1.663833
4170  1025   540115.0          EP RUKORE            PUBLIC              PRIMARY     KAYONZA      GAHINI        KAHI       RUKORE -1.783444
4136   429   130211.0         GS MURAMBI            PUBLIC                12YBE    KICUKIRO     GATENGA     KARAMBO       RUHUKA -1.981222
4148   740   421717.0          EP REMERA            PUBLIC  PRE_PRIMARY,PRIMARY       NGOMA      REMERA     KINUNGA      MURAMBI -2.076056
4133   388   230607.0         GS MUGANZA  GOVERNMENT_AIDED                12YBE   NYARUGURU     MUGANZA     MUGANZA   NYABIRONDO -2.737739
4178  1070   540305.0          EP RUSAVE  GOVERNMENT_AIDED              PRIMARY     KAYONZA   KABARONDO    CYINZOVU   AGASHIKIRI -2.003833
4195  3429   330423.0  HOUSE OF CHILDREN           PRIVATE              PRIMARY      RUBAVU     GISENYI  MBUGANGARI  IYOBOKAMANA -1.673139
4169  1024   540106.0           EP TSIMA            PUBLIC              PRIMARY     KAYONZA      GAHINI        KAHI        TSIMA -1.837028


DataComPy Comparison
--------------------

DataFrame Summary
-----------------

  DataFrame  Columns  Rows
0    Master       20  4093
1       ITU       24  4197

Column Summary
--------------

Number of columns in common: 5
Number of columns in Master but not in ITU: 15
Number of columns in ITU but not in Master: 19

Row Summary
-----------

Matched on: giga_school_id
Any duplicates on match values: No
Absolute Tolerance: 0
Relative Tolerance: 0
Number of rows in common: 4,093
Number of rows in Master but not in ITU: 0
Number of rows in ITU but not in Master: 104

Number of rows with some compared columns unequal: 0
Number of rows with all compared columns equal: 4,093

Column Comparison
-----------------

Number of columns compared with some values unequal: 0
Number of columns compared with all values equal: 5
Total number of values which compare unequal: 0

Sample Rows Only in ITU (First 10 Columns)
------------------------------------------

       fid    sn  school_id     school_nam        school_cat           school_set    district      sector        cell        village
4161   977   977   540603.0      EP GACACA  GOVERNMENT_AIDED              PRIMARY     KAYONZA     MURUNDI  RYAMANYONI        NGARAMA
4160   976   976   411602.0      EP NYUNDO  GOVERNMENT_AIDED              PRIMARY     RULINDO   SHYORONGI      RUBONA         KIGALI
4191  1342  1342   110207.0     EP MUGANZA            PUBLIC              PRIMARY  NYARUGENGE  KIMISAGARA  KIMISAGARA        MUGANZA
4155   925   925   561004.0  EP RUGARAGARA  GOVERNMENT_AIDED              PRIMARY       NGOMA      RUKIRA      NYINYA        KIBIMBA
4165   997   997   540429.0   EP NYABUBARE  GOVERNMENT_AIDED              PRIMARY     KAYONZA   MUKARANGE       BWIZA  ABEMERAMAHORO
4175  1055  1055   251403.0    EP GASHWATI  GOVERNMENT_AIDED              PRIMARY   NYAMAGABE     MUSHUBI    GASHWATI       GASHWATI
4179  1090  1090   331205.0    EP KABIRIZI            PUBLIC              PRIMARY      RUBAVU    RUGERERO    KABILIZI      RUHANGIRO
4111   203   203   410608.0      GS NGANZO            PUBLIC                12YBE     RULINDO      CYUNGO     MAREMBO         RUSAYU
4145   621   621   130523.0     EP BYIMANA            PUBLIC  PRE_PRIMARY,PRIMARY     KAYONZA       NDEGO     BYIMANA        NYAMATA
4189  1309  1309   130608.0    EP KIGARAMA            PUBLIC              PRIMARY   RWAMAGANA       NZIGE    KIGARAMA         MIKONI


DataComPy Comparison
--------------------

DataFrame Summary
-----------------

  DataFrame  Columns  Rows
0    Master       20  4093
1      GSMA       22  4197

Column Summary
--------------

Number of columns in common: 5
Number of columns in Master but not in GSMA: 15
Number of columns in GSMA but not in Master: 17

Row Summary
-----------

Matched on: giga_school_id
Any duplicates on match values: No
Absolute Tolerance: 0
Relative Tolerance: 0
Number of rows in common: 4,093
Number of rows in Master but not in GSMA: 0
Number of rows in GSMA but not in Master: 104

Number of rows with some compared columns unequal: 0
Number of rows with all compared columns equal: 4,093

Column Comparison
-----------------

Number of columns compared with some values unequal: 0
Number of columns compared with all values equal: 5
Total number of values which compare unequal: 0

Sample Rows Only in GSMA (First 10 Columns)
-------------------------------------------

        sn  source_sch    school_nam        school_cat school_set    district    sector         cell     village  latitude
4124   319    411202.0     GS GASEKE            PUBLIC      12YBE     RULINDO     NGOMA  MUNYARWANDA      BUSIZI -1.820306
4107   192    410503.0    GS GIHINGA  GOVERNMENT_AIDED      12YBE     RULINDO  CYINZUZI  BUDAKIRANYA     GIHINGA -1.757333
4192  1345    110107.0     EP GITEGA            PUBLIC    PRIMARY  NYARUGENGE    GITEGA     KINYANGE     UBUREZI -1.959778
4141   564    280204.0     ES KARAMA  GOVERNMENT_AIDED      12YBE     KAMONYI    KARAMA       BITARE     KINKERI -1.962083
4125   322    320403.0     GS KIVUMU  GOVERNMENT_AIDED      12YBE     RUTSIRO    KIVUMU     BUNYUNJU  TARAFIPORO -1.779000
4154   924    280504.0  EP NYAGISOZI  GOVERNMENT_AIDED    PRIMARY     KAMONYI    MUGINA        NTEKO   NYAGISOZI -2.091278
4101    67    270832.0     GS MUTARA            PUBLIC     12 YBE     RULINDO    RUKOZO       BURARO     RUKINGU -1.652222
4129   343    350207.0     GS RUBONA  GOVERNMENT_AIDED      12YBE   NGORORERO   GATUMBA      GATSIBO       GATWA -1.963306
4187  1238    520339.0     EP GITEGA            PUBLIC    PRIMARY   NGORORERO   HINDIRO     RUNYINYA     MAREMBO -1.795194
4121   274    411104.0    GS MURAMBI            PUBLIC      12YBE     RULINDO   MURAMBI    MUGAMBAZI    KIGARAMA -1.793639

In [8]:
# they usually don't come with "coverage" colunms, we create it at source level using the following codes

In [66]:
d_e['coverage'] = np.where((d_e['2G_coverage']== 'None') & (d_e['3G_coverage']== 'None')& (d_e['4G_coverage']== 'None'), 'NO', 'YES')
d_f['coverage'] = np.where((d_f['percent_2g'].isnull()) & (d_f['percent_3g'].isnull())& (d_f['percent_4g'].isnull()), 'NO', 'YES')
d_f['coverage'] = np.where((d_f['percent_2g']<=0) & (d_f['percent_3g']<=0) & (d_f['percent_4g']<=0), 'NO', 'YES')
d_i['coverage'] = np.where((d_i['2G'].isnull()) & (d_i['3G'].isnull())& (d_i['4G'].isnull()), 'NO', 'YES')
d_g['coverage'] = np.where((d_g['2G'].isnull()) & (d_g['3G'].isnull())& (d_g['4G'].isnull()), 'NO', 'YES')

In [10]:
# create the 2G, 3G and 4G coverage columns with binary values at source level using the following codes

In [70]:
d_g['2G_coverage'] = np.where((d_g['2G'].isnull()), 'NO', 'YES') 
d_g['3G_coverage'] = np.where((d_g['3G'].isnull()), 'NO', 'YES') 
d_g['4G_coverage'] = np.where((d_g['4G'].isnull()), 'NO', 'YES')

In [72]:
d_f['2G_coverage'] = np.where((d_f['percent_2g'] > 0), 'YES', 'NO')
d_f['3G_coverage'] = np.where((d_f['percent_3g'] > 0), 'YES', 'NO')
d_f['4G_coverage'] = np.where((d_f['percent_4g'] > 0), 'YES', 'NO')

In [73]:
d_e.rename(columns={'2G_coverage':'2G_coverage_quality', '3G_coverage':'3G_coverage_quality', '4G_coverage': '4G_coverage_quality'}, inplace=True)

In [74]:
d_e['2G_coverage'] = np.where((d_e['2G_coverage_quality'] != 'None'), 'YES', 'NO')
d_e['3G_coverage'] = np.where((d_e['3G_coverage_quality'] != 'None'), 'YES', 'NO')
d_e['4G_coverage'] = np.where((d_e['4G_coverage_quality'] != 'None'), 'YES', 'NO')
d_i['2G_coverage'] = np.where((d_i['2G'] >=1), 'YES', 'NO')
d_i['3G_coverage'] = np.where((d_i['3G'] == 1), 'YES', 'NO')
d_i['4G_coverage'] = np.where((d_i['4G'] ==1), 'YES', 'NO')

In [14]:
# they usually don't come with "coverage_type" colunms, we create it at source level using the following function and codes

In [75]:
def coverage_type(df):
    if df['4G_coverage'] == 'YES':
        return "4G"
    elif df['3G_coverage'] == 'YES':
        return "3G"
    elif df['2G_coverage'] == 'YES':
        return "2G"
    else:
        return "None"

In [76]:
d_f['coverage_type'] = d_f.apply((lambda x: coverage_type(x)),axis=1)
d_e['coverage_type'] = d_e.apply((lambda x: coverage_type(x)),axis=1)
d_i['coverage_type'] = d_i.apply((lambda x: coverage_type(x)),axis=1)
d_g['coverage_type'] = d_g.apply((lambda x: coverage_type(x)),axis=1)

In [17]:
# isolating the needed colunms from the rest

In [79]:
features = ['giga_school_id','coverage','coverage_type','2G_coverage','3G_coverage','4G_coverage']

In [81]:
d_fc = d_f[features]
d_ec = d_e[features]
d_it = d_i[features]
d_gs = d_g[features]

In [20]:
# more sanity checks for nan on giga_school_id

In [83]:
d_fc = d_fc[d_fc['giga_school_id'].notna()]
d_ec = d_ec[d_ec['giga_school_id'].notna()]
d_it = d_it[d_it['giga_school_id'].notna()]
d_gs = d_gs[d_gs['giga_school_id'].notna()]

In [22]:
# visually comparing the sources for matches and mismatches across the columns

In [84]:
df_all = pd.concat([d_fc.set_index('giga_school_id'), d_gs.set_index('giga_school_id'), d_ec.set_index('giga_school_id'),d_it.set_index('giga_school_id')], 
                   axis='columns', keys=['Facebook', 'GSMA','Ericsson', 'ITU'])
df_all.head()

               Facebook                                                    \
               coverage coverage_type 2G_coverage 3G_coverage 4G_coverage
giga_school_id
G_RWA_00112         YES            4G         YES         YES         YES
G_RWA_00116         YES            4G         YES         YES         YES
G_RWA_00258         YES            4G         YES         YES         YES
G_RWA_00551         YES            4G         YES         YES         YES
G_RWA_00901         YES            4G         YES         YES         YES

                   GSMA                                                    \
               coverage coverage_type 2G_coverage 3G_coverage 4G_coverage
giga_school_id
G_RWA_00112         YES            4G         YES         YES         YES
G_RWA_00116         YES            4G         YES         YES         YES
G_RWA_00258         YES            4G         YES         YES         YES
G_RWA_00551         YES            4G         YES         YES         YES
G_RWA_00901         YES            4G         YES         YES         YES

               Ericsson                                                    \
               coverage coverage_type 2G_coverage 3G_coverage 4G_coverage
giga_school_id
G_RWA_00112         YES            4G         YES         YES         YES
G_RWA_00116         YES            4G         YES         YES         YES
G_RWA_00258         YES            4G         YES         YES         YES
G_RWA_00551         YES            4G         YES         YES         YES
G_RWA_00901         YES            4G         YES         YES         YES

                    ITU
               coverage coverage_type 2G_coverage 3G_coverage 4G_coverage
giga_school_id
G_RWA_00112         YES            4G         YES         YES         YES
G_RWA_00116         YES            4G         YES          NO         YES
G_RWA_00258         YES            4G         YES          NO         YES
G_RWA_00551         YES            4G         YES         YES         YES
G_RWA_00901         YES            4G         YES          NO         YES

In [85]:
df_final = df_all.swaplevel(axis='columns')[d_fc.columns[1:]]
df_final.head()

               coverage                    coverage_type                    \
               Facebook GSMA Ericsson  ITU      Facebook GSMA Ericsson ITU
giga_school_id
G_RWA_00112         YES  YES      YES  YES            4G   4G       4G  4G
G_RWA_00116         YES  YES      YES  YES            4G   4G       4G  4G
G_RWA_00258         YES  YES      YES  YES            4G   4G       4G  4G
G_RWA_00551         YES  YES      YES  YES            4G   4G       4G  4G
G_RWA_00901         YES  YES      YES  YES            4G   4G       4G  4G

               2G_coverage                    3G_coverage                     \
                  Facebook GSMA Ericsson  ITU    Facebook GSMA Ericsson  ITU
giga_school_id
G_RWA_00112            YES  YES      YES  YES         YES  YES      YES  YES
G_RWA_00116            YES  YES      YES  YES         YES  YES      YES   NO
G_RWA_00258            YES  YES      YES  YES         YES  YES      YES   NO
G_RWA_00551            YES  YES      YES  YES         YES  YES      YES  YES
G_RWA_00901            YES  YES      YES  YES         YES  YES      YES   NO

               4G_coverage
                  Facebook GSMA Ericsson  ITU
giga_school_id
G_RWA_00112            YES  YES      YES  YES
G_RWA_00116            YES  YES      YES  YES
G_RWA_00258            YES  YES      YES  YES
G_RWA_00551            YES  YES      YES  YES
G_RWA_00901            YES  YES      YES  YES

In [153]:
def highlight_diff(data, color='lightcoral'):
    attr = 'background-color: {}'.format(color)
    other = data.xs('Facebook', axis='columns', level=-1)
    return pd.DataFrame(np.where(data.ne(other, level=0), attr, ''),
                        index=data.index, columns=data.columns)

#df_final.style.apply(highlight_diff, axis=None)

In [26]:
# coverage comparison report

In [87]:
# create a separate dfs
fbc = d_fc.copy()
ecc = d_ec.copy()
ituc = d_it.copy()
gsm = d_gs.copy()
# Facebook&Ericsson
cross_profile_fb_ec = datacompy.Compare(
fbc,
ecc,
join_columns='giga_school_id',  
df1_name='Facebook', 
df2_name='Ericsson'
)
# Facebook&ITU
cross_profile_fb_itu = datacompy.Compare(
fbc,
ituc,
join_columns='giga_school_id',  
df1_name='Facebook', 
df2_name='ITU'
)
#Ericsson&ITU
cross_profile_Ericsson_itu = datacompy.Compare(
ecc,
ituc,
join_columns='giga_school_id',  
df1_name='Ericsson', 
df2_name='ITU'
)
#Ericsson&ITU
cross_profile_facebook_gsma = datacompy.Compare(
fbc,
gsm,
join_columns='giga_school_id',  
df1_name='Facebook', 
df2_name='GSMA'
)

print(cross_profile_fb_ec.report())
print(cross_profile_fb_itu.report())
print(cross_profile_Ericsson_itu.report())
print(cross_profile_facebook_gsma.report())

DataComPy Comparison
--------------------

DataFrame Summary
-----------------

  DataFrame  Columns  Rows
0  Facebook        6  4195
1  Ericsson        6  4197

Column Summary
--------------

Number of columns in common: 6
Number of columns in Facebook but not in Ericsson: 0
Number of columns in Ericsson but not in Facebook: 0

Row Summary
-----------

Matched on: giga_school_id
Any duplicates on match values: No
Absolute Tolerance: 0
Relative Tolerance: 0
Number of rows in common: 4,195
Number of rows in Facebook but not in Ericsson: 0
Number of rows in Ericsson but not in Facebook: 2

Number of rows with some compared columns unequal: 2,504
Number of rows with all compared columns equal: 1,691

Column Comparison
-----------------

Number of columns compared with some values unequal: 5
Number of columns compared with all values equal: 1
Total number of values which compare unequal: 5,948

Columns with Unequal Values or Types
------------------------------------

          Column Facebook dtype Ericsson dtype  # Unequal  Max Diff  # Null Diff
3    2g_coverage         object         object        543         0            0
0    3g_coverage         object         object        426         0            0
1    4g_coverage         object         object       2375         0            0
4       coverage         object         object        218         0            0
2  coverage_type         object         object       2386         0            0

Sample Rows with Unequal Values
-------------------------------

     giga_school_id 3g_coverage (Facebook) 3g_coverage (Ericsson)
277     G_RWA_01283                    YES                     NO
282     G_RWA_02868                    YES                     NO
3957    G_RWA_02459                    YES                     NO
3604    G_RWA_00502                    YES                     NO
2811    G_RWA_02642                    YES                     NO
3819    G_RWA_03467                    YES                     NO
561     G_RWA_03529                    YES                     NO
889     G_RWA_03193                    YES                     NO
99      G_RWA_01311                    YES                     NO
914     G_RWA_00388                    YES                     NO

     giga_school_id 4g_coverage (Facebook) 4g_coverage (Ericsson)
2096    G_RWA_01858                    YES                     NO
2289    G_RWA_03285                    YES                     NO
1541    G_RWA_03094                    YES                     NO
2125    G_RWA_00552                    YES                     NO
3456    G_RWA_03455                    YES                     NO
3480    G_RWA_02640                    YES                     NO
372     G_RWA_03975                    YES                     NO
980     G_RWA_01570                    YES                     NO
4099    G_RWA_02359                    YES                     NO
2892    G_RWA_00063                    YES                     NO

     giga_school_id coverage_type (Facebook) coverage_type (Ericsson)
1257    G_RWA_02131                       4G                       3G
2628    G_RWA_04086                       4G                       3G
1978    G_RWA_02086                       4G                       3G
1439    G_RWA_02302                       4G                       3G
2345    G_RWA_00966                       4G                     None
2509    G_RWA_01208                       4G                     None
4181    G_RWA_01694                       4G                       3G
1150    G_RWA_00631                       4G                       3G
967     G_RWA_03355                       4G                       3G
2651    G_RWA_03589                       4G                       3G

     giga_school_id 2g_coverage (Facebook) 2g_coverage (Ericsson)
1770    G_RWA_03428                    YES                     NO
4174    G_RWA_00738                    YES                     NO
1916    G_RWA_01095                    YES                     NO
288     G_RWA_00577                    YES                     NO
3569    G_RWA_02031                    YES                     NO
1319    G_RWA_03581                    YES                     NO
3439    G_RWA_00548                    YES                     NO
978     G_RWA_01334                    YES                     NO
832     G_RWA_02063                    YES                     NO
3002    G_RWA_01506                    YES                     NO

     giga_school_id coverage (Facebook) coverage (Ericsson)
1938    G_RWA_01704                 YES                  NO
3961    G_RWA_02831                 YES                  NO
1458    G_RWA_02071                 YES                  NO
2514    G_RWA_01683                 YES                  NO
877     G_RWA_01240                 YES                  NO
3437    G_RWA_00515                 YES                  NO
846     G_RWA_03362                 YES                  NO
663     G_RWA_02701                 YES                  NO
1984    G_RWA_03203                 YES                  NO
2879    G_RWA_00974                 YES                  NO

Sample Rows Only in Ericsson (First 10 Columns)
-----------------------------------------------

     giga_school_id coverage coverage_type 2g_coverage 3g_coverage 4g_coverage
4195    G_RWA_02451      YES            4G         YES         YES         YES
4196    G_RWA_02626      YES            4G         YES         YES         YES


DataComPy Comparison
--------------------

DataFrame Summary
-----------------

  DataFrame  Columns  Rows
0  Facebook        6  4195
1       ITU        6  4197

Column Summary
--------------

Number of columns in common: 6
Number of columns in Facebook but not in ITU: 0
Number of columns in ITU but not in Facebook: 0

Row Summary
-----------

Matched on: giga_school_id
Any duplicates on match values: No
Absolute Tolerance: 0
Relative Tolerance: 0
Number of rows in common: 4,195
Number of rows in Facebook but not in ITU: 0
Number of rows in ITU but not in Facebook: 2

Number of rows with some compared columns unequal: 3,420
Number of rows with all compared columns equal: 775

Column Comparison
-----------------

Number of columns compared with some values unequal: 5
Number of columns compared with all values equal: 1
Total number of values which compare unequal: 4,973

Columns with Unequal Values or Types
------------------------------------

          Column Facebook dtype ITU dtype  # Unequal  Max Diff  # Null Diff
3    2g_coverage         object    object        374         0            0
0    3g_coverage         object    object       3417         0            0
1    4g_coverage         object    object        500         0            0
4       coverage         object    object        167         0            0
2  coverage_type         object    object        515         0            0

Sample Rows with Unequal Values
-------------------------------

     giga_school_id 3g_coverage (Facebook) 3g_coverage (ITU)
2481    G_RWA_02770                    YES                NO
1981    G_RWA_02659                    YES                NO
624     G_RWA_01332                    YES                NO
2328    G_RWA_02038                    YES                NO
845     G_RWA_03317                    YES                NO
1405    G_RWA_02952                    YES                NO
4078    G_RWA_02139                    YES                NO
3644    G_RWA_02033                    YES                NO
179     G_RWA_03451                    YES                NO
1254    G_RWA_01062                    YES                NO

     giga_school_id 4g_coverage (Facebook) 4g_coverage (ITU)
231     G_RWA_04055                    YES                NO
2761    G_RWA_01679                    YES                NO
3696    G_RWA_01889                    YES                NO
1387    G_RWA_03609                    YES                NO
1415    G_RWA_01640                    YES                NO
2755    G_RWA_00203                    YES                NO
1276    G_RWA_00480                    YES                NO
2398    G_RWA_00549                    YES                NO
3453    G_RWA_02711                    YES                NO
488     G_RWA_02914                    YES                NO

     giga_school_id coverage_type (Facebook) coverage_type (ITU)
3302    G_RWA_00194                       4G                None
2322    G_RWA_01292                       4G                None
371     G_RWA_03580                       4G                  2G
570     G_RWA_00716                       4G                  2G
104     G_RWA_02223                       3G                  2G
1396    G_RWA_00791                       4G                  2G
3332    G_RWA_03090                       4G                None
1987    G_RWA_04096                       4G                  2G
1118    G_RWA_03160                       4G                  2G
3661    G_RWA_01048                       4G                None

     giga_school_id 2g_coverage (Facebook) 2g_coverage (ITU)
230     G_RWA_04038                    YES                NO
444     G_RWA_03491                    YES                NO
3674    G_RWA_02983                    YES                NO
1275    G_RWA_00465                    YES                NO
797     G_RWA_00576                    YES                NO
2251    G_RWA_00669                    YES                NO
1040    G_RWA_03722                    YES                NO
4176    G_RWA_00768                    YES                NO
1546    G_RWA_03944                    YES                NO
2514    G_RWA_01683                    YES                NO

     giga_school_id coverage (Facebook) coverage (ITU)
2556    G_RWA_02150                 YES             NO
2223    G_RWA_02673                 YES             NO
1578    G_RWA_02784                 YES             NO
2962    G_RWA_03980                 YES             NO
2514    G_RWA_01683                 YES             NO
1148    G_RWA_00138                 YES             NO
278     G_RWA_01290                 YES             NO
3499    G_RWA_01944                 YES             NO
2958    G_RWA_03077                 YES             NO
1008    G_RWA_00779                 YES             NO

Sample Rows Only in ITU (First 10 Columns)
------------------------------------------

     giga_school_id coverage coverage_type 2g_coverage 3g_coverage 4g_coverage
4196    G_RWA_02626      YES            4G         YES          NO         YES
4195    G_RWA_02451      YES            4G         YES          NO         YES


DataComPy Comparison
--------------------

DataFrame Summary
-----------------

  DataFrame  Columns  Rows
0  Ericsson        6  4197
1       ITU        6  4197

Column Summary
--------------

Number of columns in common: 6
Number of columns in Ericsson but not in ITU: 0
Number of columns in ITU but not in Ericsson: 0

Row Summary
-----------

Matched on: giga_school_id
Any duplicates on match values: No
Absolute Tolerance: 0
Relative Tolerance: 0
Number of rows in common: 4,197
Number of rows in Ericsson but not in ITU: 0
Number of rows in ITU but not in Ericsson: 0

Number of rows with some compared columns unequal: 3,467
Number of rows with all compared columns equal: 730

Column Comparison
-----------------

Number of columns compared with some values unequal: 5
Number of columns compared with all values equal: 1
Total number of values which compare unequal: 8,419

Columns with Unequal Values or Types
------------------------------------

          Column Ericsson dtype ITU dtype  # Unequal  Max Diff  # Null Diff
3    2g_coverage         object    object        633         0            0
0    3g_coverage         object    object       3013         0            0
1    4g_coverage         object    object       2055         0            0
4       coverage         object    object        319         0            0
2  coverage_type         object    object       2399         0            0

Sample Rows with Unequal Values
-------------------------------

     giga_school_id 3g_coverage (Ericsson) 3g_coverage (ITU)
128     G_RWA_00129                    YES                NO
2044    G_RWA_02045                    YES                NO
131     G_RWA_00132                    YES                NO
3259    G_RWA_03260                    YES                NO
1666    G_RWA_01667                    YES                NO
2954    G_RWA_02955                    YES                NO
3758    G_RWA_03759                    YES                NO
2205    G_RWA_02206                    YES                NO
1837    G_RWA_01838                    YES                NO
645     G_RWA_00646                    YES                NO

     giga_school_id 4g_coverage (Ericsson) 4g_coverage (ITU)
641     G_RWA_00642                     NO               YES
1326    G_RWA_01327                     NO               YES
3732    G_RWA_03733                     NO               YES
3858    G_RWA_03859                     NO               YES
493     G_RWA_00494                     NO               YES
1604    G_RWA_01605                     NO               YES
2928    G_RWA_02929                     NO               YES
1461    G_RWA_01462                     NO               YES
1057    G_RWA_01058                     NO               YES
2121    G_RWA_02122                     NO               YES

     giga_school_id coverage_type (Ericsson) coverage_type (ITU)
1714    G_RWA_01715                       3G                  2G
1584    G_RWA_01585                       3G                  4G
3072    G_RWA_03073                       3G                  4G
3256    G_RWA_03257                       3G                  4G
3849    G_RWA_03850                       3G                  4G
1098    G_RWA_01099                       3G                  4G
2040    G_RWA_02041                       3G                  4G
307     G_RWA_00308                       3G                  4G
1000    G_RWA_01001                       3G                  4G
2662    G_RWA_02663                       3G                  4G

     giga_school_id 2g_coverage (Ericsson) 2g_coverage (ITU)
1802    G_RWA_01803                    YES                NO
1708    G_RWA_01709                    YES                NO
2946    G_RWA_02947                     NO               YES
812     G_RWA_00813                     NO               YES
1180    G_RWA_01181                     NO               YES
155     G_RWA_00156                     NO               YES
401     G_RWA_00402                     NO               YES
2803    G_RWA_02804                    YES                NO
1239    G_RWA_01240                     NO               YES
537     G_RWA_00538                    YES                NO

     giga_school_id coverage (Ericsson) coverage (ITU)
3285    G_RWA_03286                 YES             NO
2909    G_RWA_02910                 YES             NO
2149    G_RWA_02150                 YES             NO
377     G_RWA_00378                  NO            YES
763     G_RWA_00764                 YES             NO
237     G_RWA_00238                  NO            YES
3185    G_RWA_03186                  NO            YES
1355    G_RWA_01356                 YES             NO
104     G_RWA_00105                 YES             NO
3892    G_RWA_03893                 YES             NO


DataComPy Comparison
--------------------

DataFrame Summary
-----------------

  DataFrame  Columns  Rows
0  Facebook        6  4195
1      GSMA        6  4197

Column Summary
--------------

Number of columns in common: 6
Number of columns in Facebook but not in GSMA: 0
Number of columns in GSMA but not in Facebook: 0

Row Summary
-----------

Matched on: giga_school_id
Any duplicates on match values: No
Absolute Tolerance: 0
Relative Tolerance: 0
Number of rows in common: 4,195
Number of rows in Facebook but not in GSMA: 0
Number of rows in GSMA but not in Facebook: 2

Number of rows with some compared columns unequal: 715
Number of rows with all compared columns equal: 3,480

Column Comparison
-----------------

Number of columns compared with some values unequal: 5
Number of columns compared with all values equal: 1
Total number of values which compare unequal: 1,329

Columns with Unequal Values or Types
------------------------------------

          Column Facebook dtype GSMA dtype  # Unequal  Max Diff  # Null Diff
3    2g_coverage         object     object         27         0            0
0    3g_coverage         object     object        426         0            0
1    4g_coverage         object     object        428         0            0
4       coverage         object     object         15         0            0
2  coverage_type         object     object        433         0            0

Sample Rows with Unequal Values
-------------------------------

     giga_school_id 3g_coverage (Facebook) 3g_coverage (GSMA)
1088    G_RWA_02994                    YES                 NO
2958    G_RWA_03077                    YES                 NO
2613    G_RWA_01134                    YES                 NO
507     G_RWA_02276                    YES                 NO
1969    G_RWA_00923                    YES                 NO
3676    G_RWA_03025                    YES                 NO
3642    G_RWA_01914                    YES                 NO
1917    G_RWA_01301                    YES                 NO
190     G_RWA_01336                    YES                 NO
1184    G_RWA_03838                    YES                 NO

     giga_school_id 4g_coverage (Facebook) 4g_coverage (GSMA)
245     G_RWA_01181                    YES                 NO
2514    G_RWA_01683                    YES                 NO
838     G_RWA_02641                    YES                 NO
2706    G_RWA_02062                    YES                 NO
3513    G_RWA_04111                    YES                 NO
3665    G_RWA_01410                    YES                 NO
3572    G_RWA_02703                    YES                 NO
4156    G_RWA_02780                    YES                 NO
997     G_RWA_00251                    YES                 NO
4028    G_RWA_03187                    YES                 NO

     giga_school_id coverage_type (Facebook) coverage_type (GSMA)
1223    G_RWA_03217                       4G                   2G
2775    G_RWA_00883                       4G                   2G
455     G_RWA_00817                       4G                   2G
265     G_RWA_00007                       4G                   3G
885     G_RWA_02244                       4G                   2G
2780    G_RWA_01841                       4G                   3G
1552    G_RWA_00870                       4G                   2G
4017    G_RWA_01080                       4G                   3G
1615    G_RWA_01560                       3G                   4G
627     G_RWA_02406                       4G                   3G

     giga_school_id 2g_coverage (Facebook) 2g_coverage (GSMA)
4176    G_RWA_00768                    YES                 NO
2091    G_RWA_01084                    YES                 NO
2664    G_RWA_02218                    YES                 NO
1460    G_RWA_02379                    YES                 NO
670     G_RWA_00179                    YES                 NO
304     G_RWA_02988                    YES                 NO
663     G_RWA_02701                    YES                 NO
3141    G_RWA_01830                    YES                 NO
3294    G_RWA_02312                    YES                 NO
2856    G_RWA_01631                    YES                 NO

     giga_school_id coverage (Facebook) coverage (GSMA)
663     G_RWA_02701                 YES              NO
2539    G_RWA_02854                 YES              NO
2224    G_RWA_02822                 YES              NO
692     G_RWA_00297                 YES              NO

In [28]:
# merging and selecting the most frequent values across the sources on each row and colunm
# creating a master coverage dataset and merging with the master school location dataset

In [142]:
#Main
import statistics as stats
df_c = pd.concat([d_fc,d_gs,d_ec,d_it])
coverage = df_c.groupby(['giga_school_id'],as_index=False).agg(lambda x: stats.mode(x)[0][0])
coverage.loc[coverage['coverage'] == 'Y', 'coverage'] = 'YES'
coverage.loc[coverage['coverage'] == 'N', 'coverage'] = 'NO'
coverage.loc[coverage['2G_coverage'] == 'Y', '2G_coverage'] = 'YES'
coverage.loc[coverage['2G_coverage'] == 'N', '2G_coverage'] = 'NO'
coverage.loc[coverage['3G_coverage'] == 'Y', '3G_coverage'] = 'YES'
coverage.loc[coverage['3G_coverage'] == 'N', '3G_coverage'] = 'NO'
coverage.loc[coverage['4G_coverage'] == 'Y', '4G_coverage'] = 'YES'
coverage.loc[coverage['4G_coverage'] == 'N', '4G_coverage'] = 'NO'

coverage.loc[coverage['coverage_type'] == '4', 'coverage_type'] = '4G'
coverage.loc[coverage['coverage_type'] == '3', 'coverage_type'] = '3G'
coverage.loc[coverage['coverage_type'] == '2', 'coverage_type'] = '2G'
coverage.loc[coverage['coverage_type'] == 'N', 'coverage_type'] = 'None'

coverage.loc[coverage['coverage_type'] == 'None', 'coverage_type'] = d_fc.coverage_type

master_w_coverage = master.merge(coverage, how="left", on=["giga_school_id"])
master_w_coverage.to_csv('./data/RW_master_w_coverage.csv', encoding='utf-8')
master_w_coverage_connectivity = master_w_coverage.copy()
master_w_coverage_connectivity['connectivity'] = np.where((master_w_coverage_connectivity['connectivity_type'] != 'None'), 'YES', 'NO')
master_w_coverage_connectivity.loc[master_w_coverage_connectivity['coverage'] == 'NO', 'connectivity'] = 'NO'
master_w_coverage_connectivity.loc[master_w_coverage_connectivity['coverage'] == 'NO', 'coverage_type'] = 'None'
master_w_coverage_connectivity.loc[master_w_coverage_connectivity['coverage'] == 'NO', 'connectivity_type'] = 'None'
master_w_coverage_connectivity.to_csv('./data/RW_master_w_coverage_connectivity.csv', encoding='utf-8')

In [144]:
master_w_coverage.head()

,uuid,country,source,giga_school_id,source_school_id,school_name,education_level,latitude,longitude,hex8,...,internet_availability,number_of_students,number_of_teachers,computers,connectivity_type,coverage,coverage_type,2G_coverage,3G_coverage,4G_coverage
0,cdf4f80c-e3cc-4ebc-8931-8fe76018cc61,Rwanda,government,G_RWA_00002,521312.0,GS MUHORORO,Secondary,-2.159389,29.547972,886ade34e7fffff,...,USB_MODEM,28,1,260.0,3G,YES,4G,YES,NO,YES
1,a58be9dc-59c4-4cf9-96f5-e5b8fa84ba82,Rwanda,government,G_RWA_00005,331220.0,GS MWENDO,Secondary,-1.730639,30.212722,886ad88707fffff,...,USB_MODEM,62,3,272.0,3G,YES,4G,YES,YES,YES
2,9fe38ae7-7d51-4646-841b-1b6daa31c987,Rwanda,government,G_RWA_00006,411305.0,GS NYAGISOZI,Secondary,-2.295028,29.645556,886ade2481fffff,...,USB_MODEM,64,4,218.0,3G,YES,4G,YES,NO,YES
3,8b5c3930-c3ea-44d8-a510-086f8c6889aa,Rwanda,government,G_RWA_00009,510619.0,GS RUGANGO,Secondary,-2.371833,30.599167,886ad821d7fffff,...,USB_MODEM,80,2,252.0,3G,YES,4G,YES,YES,NO
4,2288686a-e13e-423a-b0bb-b7d08452e9a8,Rwanda,government,G_RWA_00012,130610.0,GS GIHINGA,Secondary,-1.926806,30.591806,886ad8a095fffff,...,USB_MODEM,98,3,259.0,3G,YES,4G,YES,YES,YES

In [151]:
master_w_coverage_connectivity[master_w_coverage_connectivity['coverage_type']=='None'].head(10)

,uuid,country,source,giga_school_id,source_school_id,school_name,education_level,latitude,longitude,hex8,...,number_of_students,number_of_teachers,computers,connectivity_type,coverage,coverage_type,2G_coverage,3G_coverage,4G_coverage,connectivity
838,cf2e4d25-69c8-4fea-b2a3-016ee28db593,Rwanda,government,G_RWA_00267,441003.0,GS RUTOVU,Secondary,-1.346360,29.823080,886adc3905fffff,...,1009,16,481.0,None,NO,None,NO,NO,NO,NO
2043,b470af04-ba80-4069-a457-bf4562e449d6,Rwanda,government,G_RWA_02063,441004.0,GROUPE SCOLAIRE NYABIZI,Secondary,-1.324830,29.829890,886adc3943fffff,...,244,20,NaN,None,NO,None,NO,NO,NO,NO
2647,6d23b2ce-ebd7-4815-866f-5ee49a2ddf8d,Rwanda,government,G_RWA_02701,440212.0,KILINGA,Primary,-1.362000,29.879056,886adc398dfffff,...,260,20,NaN,None,NO,None,NO,NO,NO,NO
3438,92f51147-d471-4f3f-878c-77221fc71d5f,Rwanda,government,G_RWA_03532,340803.0,GATINDORI,Primary,-1.731806,29.484250,886adeb4e7fffff,...,617,20,NaN,None,NO,None,NO,NO,NO,NO

In [146]:
master_w_coverage_connectivity.head()

,uuid,country,source,giga_school_id,source_school_id,school_name,education_level,latitude,longitude,hex8,...,number_of_students,number_of_teachers,computers,connectivity_type,coverage,coverage_type,2G_coverage,3G_coverage,4G_coverage,connectivity
0,cdf4f80c-e3cc-4ebc-8931-8fe76018cc61,Rwanda,government,G_RWA_00002,521312.0,GS MUHORORO,Secondary,-2.159389,29.547972,886ade34e7fffff,...,28,1,260.0,3G,YES,4G,YES,NO,YES,YES
1,a58be9dc-59c4-4cf9-96f5-e5b8fa84ba82,Rwanda,government,G_RWA_00005,331220.0,GS MWENDO,Secondary,-1.730639,30.212722,886ad88707fffff,...,62,3,272.0,3G,YES,4G,YES,YES,YES,YES
2,9fe38ae7-7d51-4646-841b-1b6daa31c987,Rwanda,government,G_RWA_00006,411305.0,GS NYAGISOZI,Secondary,-2.295028,29.645556,886ade2481fffff,...,64,4,218.0,3G,YES,4G,YES,NO,YES,YES
3,8b5c3930-c3ea-44d8-a510-086f8c6889aa,Rwanda,government,G_RWA_00009,510619.0,GS RUGANGO,Secondary,-2.371833,30.599167,886ad821d7fffff,...,80,2,252.0,3G,YES,4G,YES,YES,NO,YES
4,2288686a-e13e-423a-b0bb-b7d08452e9a8,Rwanda,government,G_RWA_00012,130610.0,GS GIHINGA,Secondary,-1.926806,30.591806,886ad8a095fffff,...,98,3,259.0,3G,YES,4G,YES,YES,YES,YES